### ISSUE TITLE
Заявка на вступление

### ISSUE THREAD

**Issue by Fr0z3Nn** [i-wanna-be-a-programmer/charter#5]
1. Уровень общего образования
   * Неоконченное высшее (3 курс)
2. Общий уровень IT знаний
   * Уверенный ПК пользователь
3. Уровень владения английским языком
   * Оцениваю на В2, могу читать тех. документацию
4. Какой язык(и) программирования планируете использовать
   * Java
5. Какой уровень владения языком(ми) программирования
   * Java - 4/10
6. Название проекта (если есть). По-английски или латинскими буквами
   * wbz-api
7. Тип проекта: 
    * Веб-приложение.
8. Основная идея проекта - 2-3 предложения
   * API для интернет магазина сладостей.
9. Какую помощь ожидаете получить и в какой форме
   * Хотелось бы получить помощь в виде некоторого code review.
10. Приблизительная дата создания первой (MVP) версии вашего проекта
    * 08.01.2020
11. Ваш часовой пояс
    * UTC +3 (Moscow)

**Comment by Vaysman** [comment]
заявка отправлена на почту
