### ISSUE TITLE
Заявка на вступление

### ISSUE THREAD

**Issue by Shymbolat** [i-wanna-be-a-programmer/charter#7]
1. Уровень общего образования
   * Высшее образование
2. Общий уровень IT знаний
   * больше года работаю в сфере IT
3. Уровень владения английским языком
   * Intermediate (Средний)
4. Какой язык(и) программирования планируете использовать
   * БД - PostgreSQL, BackEnd - Spring, FrontEnd - Angular
5. Какой уровень владения языком(ми) программирования
   * Могу писать простые Pet-проекты
6. Название проекта (если есть). По-английски или латинскими буквами
   * пока нет
7. Тип проекта: 
    * веб-приложение
8. Основная идея проекта - 2-3 предложения
   * Планирую реализовать веб-приложение как онлайн-магазин (Клиенты и поставщики). Пока как точно будет выглядет сайт не могу сказать.
9. Какую помощь ожидаете получить и в какой форме
   *  В начале по стек технологиям, потом по архитектуре (возможно много вопросов будут,  главное чтобы вы подсказывали правильно ли я иду)
10. Приблизительная дата создания первой (MVP) версии вашего проекта
    * Думаю этот проект для меня будет сложным, поэтому первая версия будет готово через 3-4 месяца
11. Ваш часовой пояс
    * UTC+6:00

**Comment by Vaysman** [comment]
Приглашение выслано на почту. После того, как придумаете название проекта - создам репозиторий.
