### ISSUE TITLE
Заявка на вступление

### ISSUE THREAD

**Issue by OldMan35** [i-wanna-be-a-programmer/charter#9]
1. Уровень общего образования
   * высшее
2. Общий уровень IT знаний
   * слабый
3. Уровень владения английским языком
   * А2
4. Какой язык(и) программирования планируете использовать
   * java
5. Какой уровень владения языком(ми) программирования
   * слабый
6. Название проекта (если есть). По-английски или латинскими буквами
   * Сurrency Сonverter
7. Тип проекта: 
    * веб-приложение
8. Основная идея проекта - 2-3 предложения
   * ковнертация по курсу на текущую дату, предполагается использовать json с курсами валюты, spring boot, gradle
9. Какую помощь ожидаете получить и в какой форме
   * консультационную помощь в форме вопрос-ответ
10. Приблизительная дата создания первой (MVP) версии вашего проекта
    * 01.06.2021
11. Ваш часовой пояс
    * мск

**Comment by Vaysman** [comment]
репозиторий и команда создана. приглашение выслано.
